### ISSUE TITLE
Update information on resources

### ISSUE THREAD

**Issue by conslo** [martyzz1/heroku3.py#1]
Before I possibly dove into a PR for this, I was wondering if there was functionality to update the information on a resource (process formation, dyno, etc), ie:
```Python
h = heroku3.from_key(API_KEY)
app = h.apps()[APP_NAME]
formation = app.process_formation()
web = formation['web']
print(web.quantity)
>>> 1
# time passes, a sleep, or what have you
web.some_update_method()
print(web.quantity)
>>> 3
```
because constantly using:
```Python
app.process_formation()['web'].quantity
```
is just silly, I should be able to update *just* the resource i want.

----
Maybe a more relevant example:
```Python
new_dyno = app.run_process_detached(SOME_COMMAND)
print new_dyno.state
>>> u'starting'
# Some time passes, I start other dynos, enter a sleep loop
new_dyno.some_update_command()
print new_dyno.state
>>> u'shutdown' # I don't actually know what this status is
```
Presently, the only way I know how to do this with a dyno is to attempt a lookup on the `.dynos()` method:
```Python
new_dyno = app.run_process_detached(SOME_COMMAND)
print new_dyno.state
>>> u'starting'
# Time passes
try:
    app.dynos()[new_dyno.id]
    print('still running')
except KeyError:
    print('dyno stopped')
```
Which is, again, silly. Please let me know if there's already a way to do this (I couldn't find it in the documentation), if not I'll try to find cycles to attempt this.

**Comment by martyzz1** [comment]
closing this issues as pending PR for a year...
