### ISSUE TITLE
Is it possible to create SSL endpoints with this?

### ISSUE THREAD

**Issue by mrmikardo** [martyzz1/heroku3.py#110]
This functionality is exposed by the Platform API: https://devcenter.heroku.com/articles/platform-api-reference#ssl-endpoint-create

But I couldn't figure out how to achieve that using `heroku3`.

**Comment by mrmikardo** [comment]
I am working on a PR for this 👍

**Comment by martyzz1** [comment]
thats Great. Thank yoou

**Comment by mrmikardo** [comment]
Have tested this by attempting to make a request through the API, which returns an error: "The SSL Endpoint add-on needs to be installed on this app to manage endpoints." 

But the SSL Endpoint add-on is now deprecated: https://devcenter.heroku.com/changelog-items/2145

Might be possible to implement similar functionality with the SNI Endpoints API: https://devcenter.heroku.com/articles/platform-api-reference#sni-endpoint

**Comment by mrmikardo** [comment]
@martyzz1 PR here: https://github.com/martyzz1/heroku3.py/pull/111

Please let me know what you think!
