### ISSUE TITLE
Domain Create endpoint API has changed

### ISSUE THREAD

**Issue by mrmikardo** [martyzz1/heroku3.py#115]
The Domain Create endpoint now requires an `sni_endpoint` parmeter: https://devcenter.heroku.com/articles/platform-api-reference#domain-create

This means that calls to `app.add_domain(...)` are now raising 422 errors.

The solution is to update the API to add the `sni_endpoint` parameter - also need to figure out exactly what SNI endpoint needs to be passed, and if/how that plays with Heroku's Automated Certificate Management (ACM).

I'm happy to look into this and make a PR for it over the next week or so.

**Comment by martyzz1** [comment]
This change was released last weekend...

https://github.com/martyzz1/heroku3.py#domains

Make sure you have upgraded to the latest version

**Comment by mrmikardo** [comment]
@martyzz1 many thanks for pointing this out, my bad for not spotting that - I will upgrade our copy of the library now.
