### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.heroku.com/apps

### ISSUE THREAD

**Issue by botbnb** [martyzz1/heroku3.py#117]
I often use your project, but today got 401 Client Error
Do you have any solution ?

![image](https://user-images.githubusercontent.com/88438884/143797686-a7fea48d-c4c1-4d7e-8ac8-62035d9e08cd.png)

![image](https://user-images.githubusercontent.com/88438884/143797718-c3c37bf1-1889-4894-bb72-176c6eb03922.png)

**Comment by martyzz1** [comment]
Is this still happenning?  Are you able to use that key from the heroku cli?

https://devcenter.heroku.com/articles/authentication

**Comment by botbnb** [comment]
Thanks for the hint, I checked again and found my Heroku API Key has been deleted for unknown reasons.
Thank you very much !

**Comment by martyzz1** [comment]
no worries..
