### ISSUE TITLE
size=1 default argument for run_command_detached and run_command gives an error

### ISSUE THREAD

**Issue by baka101** [martyzz1/heroku3.py#14]
This line: 
https://github.com/martyzz1/heroku3.py/blob/master/heroku3/models/app.py#L214

Not specifying size results in the size argument defaulting to 1, which is invalid.

Error from Heroku:
422 Client Error: {"id":"invalid_params","message":"No such size as 1. Available dyno sizes are Free, Hobby, Standard-1X, Standard-2X, Performance-M and Performance-L."}

**Comment by martyzz1** [comment]
ahhh the joys of the new Dyno plans...

thanks for the headsup...  I could default it to "Free", but I'll need to check the api, as this might not be  the right solution

**Comment by martyzz1** [comment]
untested fix here

Removed default size..

https://github.com/martyzz1/heroku3.py/pull/15
