### ISSUE TITLE
Detect if worker-scaling is done

### ISSUE THREAD

**Issue by yltang52** [martyzz1/heroku3.py#20]
I am trying to scale up a worker to handle a background job, and when the job is done, scale down the worker, as follows: 

    apiKey = '...'
    appName = '...'

    # Start a worker
    heroku_conn = heroku3.from_key(apiKey)
    app = heroku_conn.apps()[appName]
    app.process_formation()['worker'].scale(1)

    # Enqueue the background job
    # time.sleep(10) --> How do I know if the worker is ready?
    q = Queue(connection=conn)
    q.enqueue(backgroundJob)

In another file:

    def backgroundJob():
        # This is the background job
        ...
        # Turn off the worker
        app.process_formation()['worker'].scale(0)

My question:  How do I know if the worker is ready? The following code doesn't seem to work:

    while 'worker.1' not in app.dynos():
        time.sleep(1)

Thanks.

**Comment by martyzz1** [comment]
Sorry for not replying sooner...  Did you look at the app.process_formation() function?

**Comment by yltang52** [comment]
Thanks for your response, but I have no idea  how to use `process_formation()` to check if the worker is ready for running background jobs. The following doesn't work:

    while heroku_conn.apps()[appName].process_formation()['worker'] is None:
        time.sleep(1)

**Comment by martyzz1** [comment]
take a look at this code

https://github.com/martyzz1/heroku_proc_scalar/blob/27ab80afaa8553f29cbddb56592531d70f9f668c/heroku_proc_scalar/utils.py#L27

I think also that there was an issue with the scale command on heroku. and I wrote a wrapper function

heroku_app.scale_formation_process('worker', 1)

**Comment by yltang52** [comment]
Those programs seem to be checking the **formation** of the app (which is specified by `Procfile`), but not the **currently, actually running `web` or `worker`** of the app. Am I getting this right?

**Comment by martyzz1** [comment]
apologies for the slow response... I think that you need to look at the quantity property 
https://devcenter.heroku.com/articles/platform-api-reference#formation

if you have 0 Worker processes set to be running, then you know that when quantity=1 the worker is started.   However, I think that you are possibly doing this in the wrong way.

Why aren't you using the 
dyno = app.run_command('fab -l', printout=True)
https://github.com/martyzz1/heroku3.py/blob/2b73e78282bb6607fbeb7cbc20a8627aa8bd3056/heroku3/models/app.py#L217

This will fire up an ad hoc dyno, run your process, and exit the dyno when your process exits...

**Comment by yltang52** [comment]
I got the following message when I run `app.run_command(...)`

    Cannot run more than 1 Free size dynos

Does this command create a `one-off dyno`?

**Comment by martyzz1** [comment]
Yes...

**Comment by yltang52** [comment]
I know the answer to question1: the parameter `attach=False` is required.
