### ISSUE TITLE
Wrong "python-dateutil" version

### ISSUE THREAD

**Issue by yltang52** [martyzz1/heroku3.py#21]
Currently `pip heroku3` will automatically install the following:

    heroku3==3.2.0
    python-dateutil==1.5
    requests==2.12.0
    simplejson==3.3.1

The latest version of `python-dateutil` is 2.6.0, and version 1.5 will cause run time errors.

**Comment by martyzz1** [comment]
oops. missed the change to setup.py   pushed in master, will make a new pypi release.

**Comment by martyzz1** [comment]
v3.2.1 pushed to pypi
