### ISSUE TITLE
Exception with Python 2.7.12

### ISSUE THREAD

**Issue by nickbaum** [martyzz1/heroku3.py#26]
It seems like the version of RendezVous included isn't Python 2.X compatible:

"""
File "heroku3/__init__.py", line 27, in <module>
    from .core import from_key
  File "heroku3/core.py", line 10, in <module>
    from .api import Heroku
  File "heroku3/api.py", line 13, in <module>
    from .models.app import App
  File "heroku3/models/app.py", line 2, in <module>
    from ..rendezvous import Rendezvous
  File "heroku3/rendezvous.py", line 6, in <module>
    from urllib.parse import urlparse, uses_netloc
ImportError: No module named parse
"""

**Comment by martyzz1** [comment]
Hi Nick,

Thanks for this. Are you using latest master? or the pypi version?

**Comment by martyzz1** [comment]
Think it was caused by this commit   https://github.com/martyzz1/heroku3.py/commit/e3567662f7d7958a279c911ee477ce5fe2229a4e @yltang52

**Comment by nickbaum** [comment]
Thanks for looking into it!

This was with Heroku3 3.2.1 from pypi.

**Comment by josegonzalez** [comment]
@martyzz1 the fix seems to be fine, can you make a release of heroku3?

**Comment by yltang52** [comment]
I thought `heroku3.py` is for python3 and `heroku.py` is for python2. Is that correct?

**Comment by nickbaum** [comment]
@yltang52 nope, Heroku3 is for version 3 of the Heroku API.

**Comment by pfugate** [comment]
Please add the correction into the release from pypi. Its still the broken code.

**Comment by martyzz1** [comment]
3.2.2 now released to PyPi... apologies for the slow release on this, I've been snowed...

**Comment by josegonzalez** [comment]
Thanks for all your work!
