### ISSUE TITLE
Issues when listing objects + misc issues

### ISSUE THREAD

**Issue by gregsadetsky** [martyzz1/heroku3.py#28]
Hey there,

Thanks for the great wrapper! I stumbled upon a few things while using it to automate Heroku:

- It would be useful if the `App` object had an `organization` object with `id` and `name` just as the API [returns](https://devcenter.heroku.com/articles/platform-api-reference#app-attributes).

- When the list of addons is empty, `app.addons()` should be `False` to enable `if not app.addons()` checks. Right now, an empty addon list is evaluated as `True`.

    Generally speaking, `KeyedListResource` should probably implement `__len__`

- Passing `name` to `app.addons()` does not work to filter / find a specific addon -- the `name` keyword is ignored.

    i.e., `app.addons(name='bleh')` will return the full list of addons

Thank you!

**Comment by martyzz1** [comment]
thanks for the feedback. I'll have a think... Are you using latest master or the pypi version?

**Comment by gregsadetsky** [comment]
Latest master. Thanks!

**Comment by gregsadetsky** [comment]
The #30 PR addresses all of the points above.

`app.addons().get('addonname')` can now be called to get a single installed addon instance (I added `name` to the list of primary keys).

Addons have unique installed unique names on Heroku -- I was looking to filter them by plan name (to get all postgresql installs, for example), but the Heroku API does not seem to support this. I didn't add this functionality to the wrapper since this is trivial to do using a list comprehension.

Thanks!
