### ISSUE TITLE
Start and top the one-off dyno

### ISSUE THREAD

**Issue by yltang52** [martyzz1/heroku3.py#32]
I am using heroku3 to start a one-off dyno and then stop it when the job is done.

    # Start a one-off dyno
    apiKey = 'xxxx...'
    appName = 'yyyy...'
    heroku_conn = heroku3.from_key(apiKey)
    app = heroku_conn.apps()[appName]
    if 'run.1' in app.dynos:
        print('Another one-off dyno is running.')
    else:
        app.run_command_detached('python -m theModuleToRun')\

    "theModuleToRun.py":
    # Perform some job
    # ...
    # Stop the one-off dyno when the job is done
    apiKey = 'xxxx...'
    appName = 'yyyy...'
    heroku_conn = heroku3.from_key(apiKey)
    app = heroku_conn.apps()[appName]
    if 'run.1' in app.dynos:
        app.dynos['run.1'].kill()

My question:
Is the code to start and stop the dyno correct? Is the name of the one-off dyno always `run.1`, given that there is only one one-off dyno running at the same time?

**Comment by martyzz1** [comment]
This is more of a question of how heroku works. As long as your process exits when its finished the dyno will end.

So you don't need to do the stopping manually.
