### ISSUE TITLE
Running multiple one-off-dyno commands

### ISSUE THREAD

**Issue by yltang52** [martyzz1/heroku3.py#44]
I am trying to run two (or more) consecutive jobs on one-off dynos using heroku3 as follows:

    import heroku3

    heroku_conn = heroku3.from_key(apiKey)
    app = heroku_conn.apps()[appName]
    app.run_command_detached(command1)

    heroku_conn = heroku3.from_key(apiKey)
    app = heroku_conn.apps()[appName]
    app.run_command_detached(command2)

Question:
Supposing only one one-off dyno is allowed (for the free option) on Heroku, which of the followings would happen?

    1. Run both jobs *concurrently* on the same dyno
    2. Run the first one, and then the second one after the first finishes
    3. Run the first one, but not the second one.
    4. Overall, what's the better way of running *consecutive* jobs using one-off dynos?

Thanks.

**Comment by martyzz1** [comment]
I'd use celery. You could start and stop celery Dyno if you know when there
will be jobs. I have code for this in my repo...

**Comment by yltang52** [comment]
Got it. Thanks a lot.
