### ISSUE TITLE
python-dateutil version restriction causing dependency conflicts

### ISSUE THREAD

**Issue by SimKennedy** [martyzz1/heroku3.py#62]
Hi there,

Is there a reason heroku3 needs the exact version for python-dateutil==2.6.0?
We get an error when installing after other packages which install a later version. 

```
error: python-dateutil 2.7.2 is installed but python-dateutil==2.6.0 is required by set(['heroku3'])
```
I imagine both simplejson and python-dateutil will maintain backward compatibility, so could the _install-requires_ be changed to this?

```
required = [
    'requests>=1.2.3',
    'simplejson>=3.3.1',
    'python-dateutil>=2.6.0',
]
```

**Comment by cans** [comment]
All the CI builds I recently ran were using python-dateutils 2.7.3. Though coverage is still fairly low, I think we could go ahead and change this as suggested.
