### ISSUE TITLE
Problems calling run_command_on_app

### ISSUE THREAD

**Issue by bits01** [martyzz1/heroku3.py#78]
(1) Default `size=1` arg is not a valid value, it seems it needs a string `size='Standard-1X'`, etc.

(2) The dyno can be very slow to start (took over 40 sec. in one test) and the Rendezvous SSL read times out. The problem seems to be this line:
https://github.com/martyzz1/heroku3.py/blob/master/heroku3/rendezvous.py#L40
Can the socket timeout be customized or turned off for `run_command_on_app`?

**Comment by martyzz1** [comment]
Hi bits01,

I'd be happy to take a PR for the fixes... I'm swamped right now with a new project and won't get time to look into it for a few weeks... :(  sorry...

**Comment by bits01** [comment]
Sent PR #79 but it seems there are some CI issues.

**Comment by martyzz1** [comment]
I merged this btw... apologies for the long wait time.
