### ISSUE TITLE
simplejson dependency is pinned to version 3.3.1

### ISSUE THREAD

**Issue by MDziwny** [martyzz1/heroku3.py#84]
I'm using the version 3.4.0 of heroku3 and 1 of the requirement is simplejson which is pinned to version `simplejson==3.3.1`.

It's problematic because it conflicts with other packages using a higher version number, in my case `simplejson>=3.16.0`.

Would it be possible to use `simplejson>=3.3.1,<4` ?

**Comment by martyzz1** [comment]
Could you submit a pr? For it...

**Comment by MDziwny** [comment]
I wanted to do it but I've noticed that this package is not anymore declared in the requirements declared in `setup.py`:

https://github.com/martyzz1/heroku3.py/blob/601a1f5fcae64a62ae6e17eb9befb899f8aba95b/setup.py#L17

**Comment by martyzz1** [comment]
ah, apologies...  This was already done

https://github.com/martyzz1/heroku3.py/pull/73

Are you using the latest version?

**Comment by MDziwny** [comment]
No, I'm installing it through pypi https://pypi.org/project/heroku3/

``` python
pip install heroku3==heroku3==3.4.0
```

**Comment by martyzz1** [comment]
you could use

```
   pip install git+https://github.com/martyzz1/heroku3.py
```

**Comment by MDziwny** [comment]
Yes, it's ok in a dev environment but we're using this tool in a lot of scripts, which are sometime included in a docker image, and it's not nice to depend on a git repository (caching is not working fine, more prone to changes, ...)

**Comment by martyzz1** [comment]
I completely understand, and at some point when I have time to test out all the various PR's I merged recently, I will make a new release to pypi...
In the meantime, I'd suggest you use the github link directly, but pin it to a commit that you are happy with.  I run many production projects, and not all the libraries we use are on pypi, and pinning to a commit in a branch on github works perfectly fine.

```
    pip install git+https://github.com/martyzz1/heroku3.py@bd3e24a
```

**Comment by martyzz1** [comment]
going to close this for now...
