### ISSUE TITLE
Duplicating the CLI ps:exec functionality

### ISSUE THREAD

**Issue by bannerp87a** [martyzz1/heroku3.py#91]
the CLI has a ps:exec feature, such that one can establish a shell session via ssh to a running dyno by executing

`heroku ps:exec --app=<app-name> --dyno=<dyno-name>`

Note that this does not create a new one-off dyno, but tunnels a ssh connection to an existing/running dyno

The closest that I can find this functionality in this wrapper is `app.run_command()` , but that seems to create a new one-off dyno 

Is there a way to use this wrapper to establish an SSH (shell) connection to an existing/running dyno ?

thanks

**Comment by martyzz1** [comment]
Just to be clear - for anybody else landing here - it is impossible to connect to a running dyno on heroku. You may see the logs and thats it. 

If you want to run a command and connect to it, the app.run_command() will do that for you..
