### ISSUE TITLE
Establishing SSH shell connection to existing/running dyno ( ps:exec functionality)

### ISSUE THREAD

**Issue by grill05** [martyzz1/heroku3.py#92]
the nodejs CLI has a ps:exec feature, such that one can establish a shell session via ssh to a running dyno by executing

`heroku ps:exec --app=<app-name> --dyno=<dyno-name>
`
Note that this does not create a new one-off dyno, but tunnels a ssh connection to an existing/running dyno. In this case, the dyno does not have to be a one-off dyno, and can be a web/worker type dyno as well.

The closest that I can find this functionality in this wrapper is `app.run_command() `, but that seems to create a new one-off dyno

Is there a way to use this wrapper to establish an SSH (shell) connection to an existing/running dyno ?

**Comment by martyzz1** [comment]
There currently isn't. Pull requests accepted...

**Comment by grill05** [comment]
@martyzz1  I'd love to add this via a PR, but I cant find the correct endpoint in the REST API. The nodejs CLI does manage to execute the various `ps:` commands ( `ps:exec` , `ps:socks` etc), so there should be some corresponding API endpoint.

The closest match I could find was "attach_url" returned b the app endpoint. Any ideas on where this functionality might exists in the REST API ?

**Comment by martyzz1** [comment]
I've had a quick look. it doesn't look like the exec feature has been exposed to the API yet....  So looks like nothing we can do for now...

**Comment by grill05** [comment]
Hmm...thats too bad. I'm new to nodejs, but if I can figure out how the cli is establishing a connection, I'll make a PR

**Comment by martyzz1** [comment]
closing for now as its not something the API supports.
