### ISSUE TITLE
no support for pg?

### ISSUE THREAD

**Issue by GoldenMouse** [martyzz1/heroku3.py#93]
It doesn't seem like this library supports any postgres actions. Like `heroku pg:info`. Is that correct?

**Comment by allardbrain** [comment]
Heroku itself doesn't expose any Postgres functionality in its API beyond managing a Postgres instance as an Add-On (adding, destroying, attaching, etc.)

**Comment by GoldenMouse** [comment]
@allardbrain yes, I spent awhile perusing their API and found nothing. What an oversight for such an important task.

**Comment by martyzz1** [comment]
@GoldenMouse I agree.  It would be useful to avoid bash scripting my db actions....
