### ISSUE TITLE
run dyno

### ISSUE THREAD

**Issue by smoothbronx** [martyzz1/heroku3.py#99]
can I run dyno of applications using this module?

**Comment by martyzz1** [comment]
yes there's an example in the examples dir..

`app = heroku_conn.app('kdsjhkszdjhgksjdhfkj')
# procs = app.process_formation()
# proc = app.process_formation()['web']
# print(proc.size)
# print(proc.quantity)
# print(procs)
# proc.scale(0)
# app.scale_formation_process('web', 1) `
